# -----------------------------------------------------
# Tokyo Night Color Palette
# -----------------------------------------------------
$storm = rgb(24283b)
$stormAlpha = 24283b

$fg = rgb(c0caf5)
$fgAlpha = c0caf5

$fg_dark = rgb(a9b1d6)
$fg_darkAlpha = a9b1d6

$fg_gutter = rgb(3b4261)
$fg_gutterAlpha = 3b4261

$dark = rgb(1f2335)
$darkAlpha = 1f2335

$dark5 = rgb(1b1f2c)
$dark5Alpha = 1b1f2c

$bg = rgb(1a1b26)
$bgAlpha = 1a1b26

$bg_highlight = rgb(292e42)
$bg_highlightAlpha = 292e42

$terminal_black = rgb(414868)
$terminal_blackAlpha = 414868

$blue = rgb(7aa2f7)
$blueAlpha = 7aa2f7

$blue0 = rgb(3d59a1)
$blue0Alpha = 3d59a1

$blue1 = rgb(2ac3de)
$blue1Alpha = 2ac3de

$blue5 = rgb(89ddff)
$blue5Alpha = 89ddff

$blue6 = rgb(b4f9f8)
$blue6Alpha = b4f9f8

$blue7 = rgb(394b70)
$blue7Alpha = 394b70

$cyan = rgb(7dcfff)
$cyanAlpha = 7dcfff

$green = rgb(9ece6a)
$greenAlpha = 9ece6a

$green1 = rgb(73daca)
$green1Alpha = 73daca

$magenta = rgb(bb9af7)
$magentaAlpha = bb9af7

$magenta2 = rgb(ff007c)
$magenta2Alpha = ff007c

$orange = rgb(ff9e64)
$orangeAlpha = ff9e64

$red = rgb(f7768e)
$redAlpha = f7768e

$yellow = rgb(e0af68)
$yellowAlpha = e0af68
